// auto-generated by x2net.xpiler

using System;
using System.Collections.Generic;
using System.Text;

using x2net;

namespace x2net
{
    public static class LinkEventType
    {
        public const int LinkSessionConnected = -10;
        public const int LinkSessionDisconnected = -11;
        public const int HandshakeReq = -12;
        public const int HandshakeResp = -13;
        public const int HandshakeAck = -14;
        public const int LinkSessionRecovered = -15;
        public const int SessionReq = -16;
        public const int SessionResp = -17;
        public const int SessionAck = -18;
        public const int SessionEnd = -19;

        private static ConstsInfo<int> info;

        static LinkEventType()
        {
            info = new ConstsInfo<int>();
            info.Add("LinkSessionConnected", -10);
            info.Add("LinkSessionDisconnected", -11);
            info.Add("HandshakeReq", -12);
            info.Add("HandshakeResp", -13);
            info.Add("HandshakeAck", -14);
            info.Add("LinkSessionRecovered", -15);
            info.Add("SessionReq", -16);
            info.Add("SessionResp", -17);
            info.Add("SessionAck", -18);
            info.Add("SessionEnd", -19);
        }

        public static bool ContainsName(string name)
        {
            return info.ContainsName(name);
        }

        public static bool ContainsValue(int value)
        {
            return info.ContainsValue(value);
        }

        public static string GetName(int value)
        {
            return info.GetName(value);
        }

        public static int Parse(string name)
        {
            return info.Parse(name);
        }

        public static bool TryParse(string name, out int result)
        {
            return info.TryParse(name, out result);
        }
    }

    public class LinkSessionConnected : Event
    {
        protected static new readonly Tag tag;

        public static new int TypeId { get { return tag.TypeId; } }

        private string linkName_;
        private bool result_;
        private object context_;

        public string LinkName
        {
            get { return linkName_; }
            set
            {
                fingerprint.Touch(tag.Offset + 0);
                linkName_ = value;
            }
        }

        public bool Result
        {
            get { return result_; }
            set
            {
                fingerprint.Touch(tag.Offset + 1);
                result_ = value;
            }
        }

        public object Context
        {
            get { return context_; }
            set
            {
                fingerprint.Touch(tag.Offset + 2);
                context_ = value;
            }
        }

        static LinkSessionConnected()
        {
            tag = new Tag(Event.tag, typeof(LinkSessionConnected), 3,
                    (int)LinkEventType.LinkSessionConnected);
        }

        public new static LinkSessionConnected New()
        {
            return new LinkSessionConnected();
        }

        public LinkSessionConnected()
            : base(tag.NumProps)
        {
        }

        protected LinkSessionConnected(int length)
            : base(length + tag.NumProps)
        {
        }

        protected override bool EqualsTo(Cell other)
        {
            if (!base.EqualsTo(other))
            {
                return false;
            }
            LinkSessionConnected o = (LinkSessionConnected)other;
            if (linkName_ != o.linkName_)
            {
                return false;
            }
            if (result_ != o.result_)
            {
                return false;
            }
            if (context_ != o.context_)
            {
                return false;
            }
            return true;
        }

        public override int GetHashCode(Fingerprint fingerprint)
        {
            var hash = new Hash(base.GetHashCode(fingerprint));
            if (fingerprint.Length <= tag.Offset)
            {
                return hash.Code;
            }
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                hash.Update(tag.Offset + 0);
                hash.Update(linkName_);
            }
            if (touched[1])
            {
                hash.Update(tag.Offset + 1);
                hash.Update(result_);
            }
            if (touched[2])
            {
                hash.Update(tag.Offset + 2);
                hash.Update(context_);
            }
            return hash.Code;
        }

        public override int GetTypeId()
        {
            return tag.TypeId;
        }

        public override Cell.Tag GetTypeTag() 
        {
            return tag;
        }

        public override Func<Event> GetFactoryMethod()
        {
            return LinkSessionConnected.New;
        }

        protected override bool IsEquivalent(Cell other, Fingerprint fingerprint)
        {
            if (!base.IsEquivalent(other, fingerprint))
            {
                return false;
            }
            LinkSessionConnected o = (LinkSessionConnected)other;
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                if (linkName_ != o.linkName_)
                {
                    return false;
                }
            }
            if (touched[1])
            {
                if (result_ != o.result_)
                {
                    return false;
                }
            }
            if (touched[2])
            {
                if (context_ != o.context_)
                {
                    return false;
                }
            }
            return true;
        }

        protected override void Describe(StringBuilder stringBuilder)
        {
            base.Describe(stringBuilder);
            stringBuilder.AppendFormat(" LinkName=\"{0}\"", linkName_.Replace("\"", "\\\""));
            stringBuilder.AppendFormat(" Result={0}", result_);
            stringBuilder.AppendFormat(" Context={0}", context_);
        }
    }

    public class LinkSessionDisconnected : Event
    {
        protected static new readonly Tag tag;

        public static new int TypeId { get { return tag.TypeId; } }

        private string linkName_;
        private int handle_;
        private object context_;

        public string LinkName
        {
            get { return linkName_; }
            set
            {
                fingerprint.Touch(tag.Offset + 0);
                linkName_ = value;
            }
        }

        public int Handle
        {
            get { return handle_; }
            set
            {
                fingerprint.Touch(tag.Offset + 1);
                handle_ = value;
            }
        }

        public object Context
        {
            get { return context_; }
            set
            {
                fingerprint.Touch(tag.Offset + 2);
                context_ = value;
            }
        }

        static LinkSessionDisconnected()
        {
            tag = new Tag(Event.tag, typeof(LinkSessionDisconnected), 3,
                    (int)LinkEventType.LinkSessionDisconnected);
        }

        public new static LinkSessionDisconnected New()
        {
            return new LinkSessionDisconnected();
        }

        public LinkSessionDisconnected()
            : base(tag.NumProps)
        {
        }

        protected LinkSessionDisconnected(int length)
            : base(length + tag.NumProps)
        {
        }

        protected override bool EqualsTo(Cell other)
        {
            if (!base.EqualsTo(other))
            {
                return false;
            }
            LinkSessionDisconnected o = (LinkSessionDisconnected)other;
            if (linkName_ != o.linkName_)
            {
                return false;
            }
            if (handle_ != o.handle_)
            {
                return false;
            }
            if (context_ != o.context_)
            {
                return false;
            }
            return true;
        }

        public override int GetHashCode(Fingerprint fingerprint)
        {
            var hash = new Hash(base.GetHashCode(fingerprint));
            if (fingerprint.Length <= tag.Offset)
            {
                return hash.Code;
            }
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                hash.Update(tag.Offset + 0);
                hash.Update(linkName_);
            }
            if (touched[1])
            {
                hash.Update(tag.Offset + 1);
                hash.Update(handle_);
            }
            if (touched[2])
            {
                hash.Update(tag.Offset + 2);
                hash.Update(context_);
            }
            return hash.Code;
        }

        public override int GetTypeId()
        {
            return tag.TypeId;
        }

        public override Cell.Tag GetTypeTag() 
        {
            return tag;
        }

        public override Func<Event> GetFactoryMethod()
        {
            return LinkSessionDisconnected.New;
        }

        protected override bool IsEquivalent(Cell other, Fingerprint fingerprint)
        {
            if (!base.IsEquivalent(other, fingerprint))
            {
                return false;
            }
            LinkSessionDisconnected o = (LinkSessionDisconnected)other;
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                if (linkName_ != o.linkName_)
                {
                    return false;
                }
            }
            if (touched[1])
            {
                if (handle_ != o.handle_)
                {
                    return false;
                }
            }
            if (touched[2])
            {
                if (context_ != o.context_)
                {
                    return false;
                }
            }
            return true;
        }

        protected override void Describe(StringBuilder stringBuilder)
        {
            base.Describe(stringBuilder);
            stringBuilder.AppendFormat(" LinkName=\"{0}\"", linkName_.Replace("\"", "\\\""));
            stringBuilder.AppendFormat(" Handle={0}", handle_);
            stringBuilder.AppendFormat(" Context={0}", context_);
        }
    }

    public class HandshakeReq : Event
    {
        protected static new readonly Tag tag;

        public static new int TypeId { get { return tag.TypeId; } }

        private byte[] data_;

        public byte[] Data
        {
            get { return data_; }
            set
            {
                fingerprint.Touch(tag.Offset + 0);
                data_ = value;
            }
        }

        static HandshakeReq()
        {
            tag = new Tag(Event.tag, typeof(HandshakeReq), 1,
                    (int)LinkEventType.HandshakeReq);
        }

        public new static HandshakeReq New()
        {
            return new HandshakeReq();
        }

        public HandshakeReq()
            : base(tag.NumProps)
        {
            Initialize();
        }

        protected HandshakeReq(int length)
            : base(length + tag.NumProps)
        {
            Initialize();
        }

        protected override bool EqualsTo(Cell other)
        {
            if (!base.EqualsTo(other))
            {
                return false;
            }
            HandshakeReq o = (HandshakeReq)other;
            if (!Extensions.EqualsExtended(data_, o.data_))
            {
                return false;
            }
            return true;
        }

        public override int GetHashCode(Fingerprint fingerprint)
        {
            var hash = new Hash(base.GetHashCode(fingerprint));
            if (fingerprint.Length <= tag.Offset)
            {
                return hash.Code;
            }
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                hash.Update(tag.Offset + 0);
                hash.Update(data_);
            }
            return hash.Code;
        }

        public override int GetTypeId()
        {
            return tag.TypeId;
        }

        public override Cell.Tag GetTypeTag() 
        {
            return tag;
        }

        public override Func<Event> GetFactoryMethod()
        {
            return HandshakeReq.New;
        }

        protected override bool IsEquivalent(Cell other, Fingerprint fingerprint)
        {
            if (!base.IsEquivalent(other, fingerprint))
            {
                return false;
            }
            HandshakeReq o = (HandshakeReq)other;
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                if (data_ != o.data_)
                {
                    return false;
                }
            }
            return true;
        }

        public override void Deserialize(Deserializer deserializer)
        {
            base.Deserialize(deserializer);
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                deserializer.Read(out data_);
            }
        }

        public override void Deserialize(VerboseDeserializer deserializer)
        {
            base.Deserialize(deserializer);
            deserializer.Read("Data", out data_);
        }

        public override int GetLength(Type targetType, ref bool flag)
        {
            int length = base.GetLength(targetType, ref flag);
            if (!flag) { return length; }
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                length += Serializer.GetLength(data_);
            }
            if (targetType != null && targetType == typeof(HandshakeReq))
            {
                flag = false;
            }
            return length;
        }

        public override void Serialize(Serializer serializer,
            Type targetType, ref bool flag)
        {
            base.Serialize(serializer, targetType, ref flag);
            if (!flag) { return; }
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                serializer.Write(data_);
            }
            if (targetType != null && targetType == typeof(HandshakeReq))
            {
                flag = false;
            }
        }

        public override void Serialize(VerboseSerializer serializer,
            Type targetType, ref bool flag)
        {
            base.Serialize(serializer, targetType, ref flag);
            if (!flag) { return; }
            serializer.Write("Data", data_);
            if (targetType != null && targetType == typeof(HandshakeReq))
            {
                flag = false;
            }
        }

        protected override void Describe(StringBuilder stringBuilder)
        {
            base.Describe(stringBuilder);
            stringBuilder.AppendFormat(" Data={0}", data_.ToStringExtended());
        }

        private void Initialize()
        {
            data_ = null;
        }
    }

    public class HandshakeResp : Event
    {
        protected static new readonly Tag tag;

        public static new int TypeId { get { return tag.TypeId; } }

        private byte[] data_;

        public byte[] Data
        {
            get { return data_; }
            set
            {
                fingerprint.Touch(tag.Offset + 0);
                data_ = value;
            }
        }

        static HandshakeResp()
        {
            tag = new Tag(Event.tag, typeof(HandshakeResp), 1,
                    (int)LinkEventType.HandshakeResp);
        }

        public new static HandshakeResp New()
        {
            return new HandshakeResp();
        }

        public HandshakeResp()
            : base(tag.NumProps)
        {
            Initialize();
        }

        protected HandshakeResp(int length)
            : base(length + tag.NumProps)
        {
            Initialize();
        }

        protected override bool EqualsTo(Cell other)
        {
            if (!base.EqualsTo(other))
            {
                return false;
            }
            HandshakeResp o = (HandshakeResp)other;
            if (!Extensions.EqualsExtended(data_, o.data_))
            {
                return false;
            }
            return true;
        }

        public override int GetHashCode(Fingerprint fingerprint)
        {
            var hash = new Hash(base.GetHashCode(fingerprint));
            if (fingerprint.Length <= tag.Offset)
            {
                return hash.Code;
            }
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                hash.Update(tag.Offset + 0);
                hash.Update(data_);
            }
            return hash.Code;
        }

        public override int GetTypeId()
        {
            return tag.TypeId;
        }

        public override Cell.Tag GetTypeTag() 
        {
            return tag;
        }

        public override Func<Event> GetFactoryMethod()
        {
            return HandshakeResp.New;
        }

        protected override bool IsEquivalent(Cell other, Fingerprint fingerprint)
        {
            if (!base.IsEquivalent(other, fingerprint))
            {
                return false;
            }
            HandshakeResp o = (HandshakeResp)other;
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                if (data_ != o.data_)
                {
                    return false;
                }
            }
            return true;
        }

        public override void Deserialize(Deserializer deserializer)
        {
            base.Deserialize(deserializer);
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                deserializer.Read(out data_);
            }
        }

        public override void Deserialize(VerboseDeserializer deserializer)
        {
            base.Deserialize(deserializer);
            deserializer.Read("Data", out data_);
        }

        public override int GetLength(Type targetType, ref bool flag)
        {
            int length = base.GetLength(targetType, ref flag);
            if (!flag) { return length; }
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                length += Serializer.GetLength(data_);
            }
            if (targetType != null && targetType == typeof(HandshakeResp))
            {
                flag = false;
            }
            return length;
        }

        public override void Serialize(Serializer serializer,
            Type targetType, ref bool flag)
        {
            base.Serialize(serializer, targetType, ref flag);
            if (!flag) { return; }
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                serializer.Write(data_);
            }
            if (targetType != null && targetType == typeof(HandshakeResp))
            {
                flag = false;
            }
        }

        public override void Serialize(VerboseSerializer serializer,
            Type targetType, ref bool flag)
        {
            base.Serialize(serializer, targetType, ref flag);
            if (!flag) { return; }
            serializer.Write("Data", data_);
            if (targetType != null && targetType == typeof(HandshakeResp))
            {
                flag = false;
            }
        }

        protected override void Describe(StringBuilder stringBuilder)
        {
            base.Describe(stringBuilder);
            stringBuilder.AppendFormat(" Data={0}", data_.ToStringExtended());
        }

        private void Initialize()
        {
            data_ = null;
        }
    }

    public class HandshakeAck : Event
    {
        protected static new readonly Tag tag;

        public static new int TypeId { get { return tag.TypeId; } }

        private bool result_;

        public bool Result
        {
            get { return result_; }
            set
            {
                fingerprint.Touch(tag.Offset + 0);
                result_ = value;
            }
        }

        static HandshakeAck()
        {
            tag = new Tag(Event.tag, typeof(HandshakeAck), 1,
                    (int)LinkEventType.HandshakeAck);
        }

        public new static HandshakeAck New()
        {
            return new HandshakeAck();
        }

        public HandshakeAck()
            : base(tag.NumProps)
        {
            Initialize();
        }

        protected HandshakeAck(int length)
            : base(length + tag.NumProps)
        {
            Initialize();
        }

        protected override bool EqualsTo(Cell other)
        {
            if (!base.EqualsTo(other))
            {
                return false;
            }
            HandshakeAck o = (HandshakeAck)other;
            if (result_ != o.result_)
            {
                return false;
            }
            return true;
        }

        public override int GetHashCode(Fingerprint fingerprint)
        {
            var hash = new Hash(base.GetHashCode(fingerprint));
            if (fingerprint.Length <= tag.Offset)
            {
                return hash.Code;
            }
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                hash.Update(tag.Offset + 0);
                hash.Update(result_);
            }
            return hash.Code;
        }

        public override int GetTypeId()
        {
            return tag.TypeId;
        }

        public override Cell.Tag GetTypeTag() 
        {
            return tag;
        }

        public override Func<Event> GetFactoryMethod()
        {
            return HandshakeAck.New;
        }

        protected override bool IsEquivalent(Cell other, Fingerprint fingerprint)
        {
            if (!base.IsEquivalent(other, fingerprint))
            {
                return false;
            }
            HandshakeAck o = (HandshakeAck)other;
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                if (result_ != o.result_)
                {
                    return false;
                }
            }
            return true;
        }

        public override void Deserialize(Deserializer deserializer)
        {
            base.Deserialize(deserializer);
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                deserializer.Read(out result_);
            }
        }

        public override void Deserialize(VerboseDeserializer deserializer)
        {
            base.Deserialize(deserializer);
            deserializer.Read("Result", out result_);
        }

        public override int GetLength(Type targetType, ref bool flag)
        {
            int length = base.GetLength(targetType, ref flag);
            if (!flag) { return length; }
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                length += Serializer.GetLength(result_);
            }
            if (targetType != null && targetType == typeof(HandshakeAck))
            {
                flag = false;
            }
            return length;
        }

        public override void Serialize(Serializer serializer,
            Type targetType, ref bool flag)
        {
            base.Serialize(serializer, targetType, ref flag);
            if (!flag) { return; }
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                serializer.Write(result_);
            }
            if (targetType != null && targetType == typeof(HandshakeAck))
            {
                flag = false;
            }
        }

        public override void Serialize(VerboseSerializer serializer,
            Type targetType, ref bool flag)
        {
            base.Serialize(serializer, targetType, ref flag);
            if (!flag) { return; }
            serializer.Write("Result", result_);
            if (targetType != null && targetType == typeof(HandshakeAck))
            {
                flag = false;
            }
        }

        protected override void Describe(StringBuilder stringBuilder)
        {
            base.Describe(stringBuilder);
            stringBuilder.AppendFormat(" Result={0}", result_);
        }

        private void Initialize()
        {
            result_ = false;
        }
    }

    public class LinkSessionRecovered : Event
    {
        protected static new readonly Tag tag;

        public static new int TypeId { get { return tag.TypeId; } }

        private string linkName_;
        private int handle_;
        private object context_;

        public string LinkName
        {
            get { return linkName_; }
            set
            {
                fingerprint.Touch(tag.Offset + 0);
                linkName_ = value;
            }
        }

        public int Handle
        {
            get { return handle_; }
            set
            {
                fingerprint.Touch(tag.Offset + 1);
                handle_ = value;
            }
        }

        public object Context
        {
            get { return context_; }
            set
            {
                fingerprint.Touch(tag.Offset + 2);
                context_ = value;
            }
        }

        static LinkSessionRecovered()
        {
            tag = new Tag(Event.tag, typeof(LinkSessionRecovered), 3,
                    (int)LinkEventType.LinkSessionRecovered);
        }

        public new static LinkSessionRecovered New()
        {
            return new LinkSessionRecovered();
        }

        public LinkSessionRecovered()
            : base(tag.NumProps)
        {
        }

        protected LinkSessionRecovered(int length)
            : base(length + tag.NumProps)
        {
        }

        protected override bool EqualsTo(Cell other)
        {
            if (!base.EqualsTo(other))
            {
                return false;
            }
            LinkSessionRecovered o = (LinkSessionRecovered)other;
            if (linkName_ != o.linkName_)
            {
                return false;
            }
            if (handle_ != o.handle_)
            {
                return false;
            }
            if (context_ != o.context_)
            {
                return false;
            }
            return true;
        }

        public override int GetHashCode(Fingerprint fingerprint)
        {
            var hash = new Hash(base.GetHashCode(fingerprint));
            if (fingerprint.Length <= tag.Offset)
            {
                return hash.Code;
            }
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                hash.Update(tag.Offset + 0);
                hash.Update(linkName_);
            }
            if (touched[1])
            {
                hash.Update(tag.Offset + 1);
                hash.Update(handle_);
            }
            if (touched[2])
            {
                hash.Update(tag.Offset + 2);
                hash.Update(context_);
            }
            return hash.Code;
        }

        public override int GetTypeId()
        {
            return tag.TypeId;
        }

        public override Cell.Tag GetTypeTag() 
        {
            return tag;
        }

        public override Func<Event> GetFactoryMethod()
        {
            return LinkSessionRecovered.New;
        }

        protected override bool IsEquivalent(Cell other, Fingerprint fingerprint)
        {
            if (!base.IsEquivalent(other, fingerprint))
            {
                return false;
            }
            LinkSessionRecovered o = (LinkSessionRecovered)other;
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                if (linkName_ != o.linkName_)
                {
                    return false;
                }
            }
            if (touched[1])
            {
                if (handle_ != o.handle_)
                {
                    return false;
                }
            }
            if (touched[2])
            {
                if (context_ != o.context_)
                {
                    return false;
                }
            }
            return true;
        }

        protected override void Describe(StringBuilder stringBuilder)
        {
            base.Describe(stringBuilder);
            stringBuilder.AppendFormat(" LinkName=\"{0}\"", linkName_.Replace("\"", "\\\""));
            stringBuilder.AppendFormat(" Handle={0}", handle_);
            stringBuilder.AppendFormat(" Context={0}", context_);
        }
    }

    public class SessionReq : Event
    {
        protected static new readonly Tag tag;

        public static new int TypeId { get { return tag.TypeId; } }

        private string token_;
        private long rxCounter_;
        private long txCounter_;
        private int txBuffered_;

        public string Token
        {
            get { return token_; }
            set
            {
                fingerprint.Touch(tag.Offset + 0);
                token_ = value;
            }
        }

        public long RxCounter
        {
            get { return rxCounter_; }
            set
            {
                fingerprint.Touch(tag.Offset + 1);
                rxCounter_ = value;
            }
        }

        public long TxCounter
        {
            get { return txCounter_; }
            set
            {
                fingerprint.Touch(tag.Offset + 2);
                txCounter_ = value;
            }
        }

        public int TxBuffered
        {
            get { return txBuffered_; }
            set
            {
                fingerprint.Touch(tag.Offset + 3);
                txBuffered_ = value;
            }
        }

        static SessionReq()
        {
            tag = new Tag(Event.tag, typeof(SessionReq), 4,
                    (int)LinkEventType.SessionReq);
        }

        public new static SessionReq New()
        {
            return new SessionReq();
        }

        public SessionReq()
            : base(tag.NumProps)
        {
            Initialize();
        }

        protected SessionReq(int length)
            : base(length + tag.NumProps)
        {
            Initialize();
        }

        protected override bool EqualsTo(Cell other)
        {
            if (!base.EqualsTo(other))
            {
                return false;
            }
            SessionReq o = (SessionReq)other;
            if (token_ != o.token_)
            {
                return false;
            }
            if (rxCounter_ != o.rxCounter_)
            {
                return false;
            }
            if (txCounter_ != o.txCounter_)
            {
                return false;
            }
            if (txBuffered_ != o.txBuffered_)
            {
                return false;
            }
            return true;
        }

        public override int GetHashCode(Fingerprint fingerprint)
        {
            var hash = new Hash(base.GetHashCode(fingerprint));
            if (fingerprint.Length <= tag.Offset)
            {
                return hash.Code;
            }
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                hash.Update(tag.Offset + 0);
                hash.Update(token_);
            }
            if (touched[1])
            {
                hash.Update(tag.Offset + 1);
                hash.Update(rxCounter_);
            }
            if (touched[2])
            {
                hash.Update(tag.Offset + 2);
                hash.Update(txCounter_);
            }
            if (touched[3])
            {
                hash.Update(tag.Offset + 3);
                hash.Update(txBuffered_);
            }
            return hash.Code;
        }

        public override int GetTypeId()
        {
            return tag.TypeId;
        }

        public override Cell.Tag GetTypeTag() 
        {
            return tag;
        }

        public override Func<Event> GetFactoryMethod()
        {
            return SessionReq.New;
        }

        protected override bool IsEquivalent(Cell other, Fingerprint fingerprint)
        {
            if (!base.IsEquivalent(other, fingerprint))
            {
                return false;
            }
            SessionReq o = (SessionReq)other;
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                if (token_ != o.token_)
                {
                    return false;
                }
            }
            if (touched[1])
            {
                if (rxCounter_ != o.rxCounter_)
                {
                    return false;
                }
            }
            if (touched[2])
            {
                if (txCounter_ != o.txCounter_)
                {
                    return false;
                }
            }
            if (touched[3])
            {
                if (txBuffered_ != o.txBuffered_)
                {
                    return false;
                }
            }
            return true;
        }

        public override void Deserialize(Deserializer deserializer)
        {
            base.Deserialize(deserializer);
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                deserializer.Read(out token_);
            }
            if (touched[1])
            {
                deserializer.Read(out rxCounter_);
            }
            if (touched[2])
            {
                deserializer.Read(out txCounter_);
            }
            if (touched[3])
            {
                deserializer.Read(out txBuffered_);
            }
        }

        public override void Deserialize(VerboseDeserializer deserializer)
        {
            base.Deserialize(deserializer);
            deserializer.Read("Token", out token_);
            deserializer.Read("RxCounter", out rxCounter_);
            deserializer.Read("TxCounter", out txCounter_);
            deserializer.Read("TxBuffered", out txBuffered_);
        }

        public override int GetLength(Type targetType, ref bool flag)
        {
            int length = base.GetLength(targetType, ref flag);
            if (!flag) { return length; }
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                length += Serializer.GetLength(token_);
            }
            if (touched[1])
            {
                length += Serializer.GetLength(rxCounter_);
            }
            if (touched[2])
            {
                length += Serializer.GetLength(txCounter_);
            }
            if (touched[3])
            {
                length += Serializer.GetLength(txBuffered_);
            }
            if (targetType != null && targetType == typeof(SessionReq))
            {
                flag = false;
            }
            return length;
        }

        public override void Serialize(Serializer serializer,
            Type targetType, ref bool flag)
        {
            base.Serialize(serializer, targetType, ref flag);
            if (!flag) { return; }
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                serializer.Write(token_);
            }
            if (touched[1])
            {
                serializer.Write(rxCounter_);
            }
            if (touched[2])
            {
                serializer.Write(txCounter_);
            }
            if (touched[3])
            {
                serializer.Write(txBuffered_);
            }
            if (targetType != null && targetType == typeof(SessionReq))
            {
                flag = false;
            }
        }

        public override void Serialize(VerboseSerializer serializer,
            Type targetType, ref bool flag)
        {
            base.Serialize(serializer, targetType, ref flag);
            if (!flag) { return; }
            serializer.Write("Token", token_);
            serializer.Write("RxCounter", rxCounter_);
            serializer.Write("TxCounter", txCounter_);
            serializer.Write("TxBuffered", txBuffered_);
            if (targetType != null && targetType == typeof(SessionReq))
            {
                flag = false;
            }
        }

        protected override void Describe(StringBuilder stringBuilder)
        {
            base.Describe(stringBuilder);
            stringBuilder.AppendFormat(" Token=\"{0}\"", token_.Replace("\"", "\\\""));
            stringBuilder.AppendFormat(" RxCounter={0}", rxCounter_);
            stringBuilder.AppendFormat(" TxCounter={0}", txCounter_);
            stringBuilder.AppendFormat(" TxBuffered={0}", txBuffered_);
        }

        private void Initialize()
        {
            token_ = "";
            rxCounter_ = 0;
            txCounter_ = 0;
            txBuffered_ = 0;
        }
    }

    public class SessionResp : Event
    {
        protected static new readonly Tag tag;

        public static new int TypeId { get { return tag.TypeId; } }

        private string token_;
        private int retransmission_;

        public string Token
        {
            get { return token_; }
            set
            {
                fingerprint.Touch(tag.Offset + 0);
                token_ = value;
            }
        }

        public int Retransmission
        {
            get { return retransmission_; }
            set
            {
                fingerprint.Touch(tag.Offset + 1);
                retransmission_ = value;
            }
        }

        static SessionResp()
        {
            tag = new Tag(Event.tag, typeof(SessionResp), 2,
                    (int)LinkEventType.SessionResp);
        }

        public new static SessionResp New()
        {
            return new SessionResp();
        }

        public SessionResp()
            : base(tag.NumProps)
        {
            Initialize();
        }

        protected SessionResp(int length)
            : base(length + tag.NumProps)
        {
            Initialize();
        }

        protected override bool EqualsTo(Cell other)
        {
            if (!base.EqualsTo(other))
            {
                return false;
            }
            SessionResp o = (SessionResp)other;
            if (token_ != o.token_)
            {
                return false;
            }
            if (retransmission_ != o.retransmission_)
            {
                return false;
            }
            return true;
        }

        public override int GetHashCode(Fingerprint fingerprint)
        {
            var hash = new Hash(base.GetHashCode(fingerprint));
            if (fingerprint.Length <= tag.Offset)
            {
                return hash.Code;
            }
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                hash.Update(tag.Offset + 0);
                hash.Update(token_);
            }
            if (touched[1])
            {
                hash.Update(tag.Offset + 1);
                hash.Update(retransmission_);
            }
            return hash.Code;
        }

        public override int GetTypeId()
        {
            return tag.TypeId;
        }

        public override Cell.Tag GetTypeTag() 
        {
            return tag;
        }

        public override Func<Event> GetFactoryMethod()
        {
            return SessionResp.New;
        }

        protected override bool IsEquivalent(Cell other, Fingerprint fingerprint)
        {
            if (!base.IsEquivalent(other, fingerprint))
            {
                return false;
            }
            SessionResp o = (SessionResp)other;
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                if (token_ != o.token_)
                {
                    return false;
                }
            }
            if (touched[1])
            {
                if (retransmission_ != o.retransmission_)
                {
                    return false;
                }
            }
            return true;
        }

        public override void Deserialize(Deserializer deserializer)
        {
            base.Deserialize(deserializer);
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                deserializer.Read(out token_);
            }
            if (touched[1])
            {
                deserializer.Read(out retransmission_);
            }
        }

        public override void Deserialize(VerboseDeserializer deserializer)
        {
            base.Deserialize(deserializer);
            deserializer.Read("Token", out token_);
            deserializer.Read("Retransmission", out retransmission_);
        }

        public override int GetLength(Type targetType, ref bool flag)
        {
            int length = base.GetLength(targetType, ref flag);
            if (!flag) { return length; }
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                length += Serializer.GetLength(token_);
            }
            if (touched[1])
            {
                length += Serializer.GetLength(retransmission_);
            }
            if (targetType != null && targetType == typeof(SessionResp))
            {
                flag = false;
            }
            return length;
        }

        public override void Serialize(Serializer serializer,
            Type targetType, ref bool flag)
        {
            base.Serialize(serializer, targetType, ref flag);
            if (!flag) { return; }
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                serializer.Write(token_);
            }
            if (touched[1])
            {
                serializer.Write(retransmission_);
            }
            if (targetType != null && targetType == typeof(SessionResp))
            {
                flag = false;
            }
        }

        public override void Serialize(VerboseSerializer serializer,
            Type targetType, ref bool flag)
        {
            base.Serialize(serializer, targetType, ref flag);
            if (!flag) { return; }
            serializer.Write("Token", token_);
            serializer.Write("Retransmission", retransmission_);
            if (targetType != null && targetType == typeof(SessionResp))
            {
                flag = false;
            }
        }

        protected override void Describe(StringBuilder stringBuilder)
        {
            base.Describe(stringBuilder);
            stringBuilder.AppendFormat(" Token=\"{0}\"", token_.Replace("\"", "\\\""));
            stringBuilder.AppendFormat(" Retransmission={0}", retransmission_);
        }

        private void Initialize()
        {
            token_ = "";
            retransmission_ = 0;
        }
    }

    public class SessionAck : Event
    {
        protected static new readonly Tag tag;

        public static new int TypeId { get { return tag.TypeId; } }

        private bool recovered_;

        public bool Recovered
        {
            get { return recovered_; }
            set
            {
                fingerprint.Touch(tag.Offset + 0);
                recovered_ = value;
            }
        }

        static SessionAck()
        {
            tag = new Tag(Event.tag, typeof(SessionAck), 1,
                    (int)LinkEventType.SessionAck);
        }

        public new static SessionAck New()
        {
            return new SessionAck();
        }

        public SessionAck()
            : base(tag.NumProps)
        {
            Initialize();
        }

        protected SessionAck(int length)
            : base(length + tag.NumProps)
        {
            Initialize();
        }

        protected override bool EqualsTo(Cell other)
        {
            if (!base.EqualsTo(other))
            {
                return false;
            }
            SessionAck o = (SessionAck)other;
            if (recovered_ != o.recovered_)
            {
                return false;
            }
            return true;
        }

        public override int GetHashCode(Fingerprint fingerprint)
        {
            var hash = new Hash(base.GetHashCode(fingerprint));
            if (fingerprint.Length <= tag.Offset)
            {
                return hash.Code;
            }
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                hash.Update(tag.Offset + 0);
                hash.Update(recovered_);
            }
            return hash.Code;
        }

        public override int GetTypeId()
        {
            return tag.TypeId;
        }

        public override Cell.Tag GetTypeTag() 
        {
            return tag;
        }

        public override Func<Event> GetFactoryMethod()
        {
            return SessionAck.New;
        }

        protected override bool IsEquivalent(Cell other, Fingerprint fingerprint)
        {
            if (!base.IsEquivalent(other, fingerprint))
            {
                return false;
            }
            SessionAck o = (SessionAck)other;
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                if (recovered_ != o.recovered_)
                {
                    return false;
                }
            }
            return true;
        }

        public override void Deserialize(Deserializer deserializer)
        {
            base.Deserialize(deserializer);
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                deserializer.Read(out recovered_);
            }
        }

        public override void Deserialize(VerboseDeserializer deserializer)
        {
            base.Deserialize(deserializer);
            deserializer.Read("Recovered", out recovered_);
        }

        public override int GetLength(Type targetType, ref bool flag)
        {
            int length = base.GetLength(targetType, ref flag);
            if (!flag) { return length; }
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                length += Serializer.GetLength(recovered_);
            }
            if (targetType != null && targetType == typeof(SessionAck))
            {
                flag = false;
            }
            return length;
        }

        public override void Serialize(Serializer serializer,
            Type targetType, ref bool flag)
        {
            base.Serialize(serializer, targetType, ref flag);
            if (!flag) { return; }
            var touched = new Capo<bool>(fingerprint, tag.Offset);
            if (touched[0])
            {
                serializer.Write(recovered_);
            }
            if (targetType != null && targetType == typeof(SessionAck))
            {
                flag = false;
            }
        }

        public override void Serialize(VerboseSerializer serializer,
            Type targetType, ref bool flag)
        {
            base.Serialize(serializer, targetType, ref flag);
            if (!flag) { return; }
            serializer.Write("Recovered", recovered_);
            if (targetType != null && targetType == typeof(SessionAck))
            {
                flag = false;
            }
        }

        protected override void Describe(StringBuilder stringBuilder)
        {
            base.Describe(stringBuilder);
            stringBuilder.AppendFormat(" Recovered={0}", recovered_);
        }

        private void Initialize()
        {
            recovered_ = false;
        }
    }

    public class SessionEnd : Event
    {
        protected static new readonly Tag tag;

        public static new int TypeId { get { return tag.TypeId; } }

        static SessionEnd()
        {
            tag = new Tag(Event.tag, typeof(SessionEnd), 0,
                    (int)LinkEventType.SessionEnd);
        }

        public new static SessionEnd New()
        {
            return new SessionEnd();
        }

        public SessionEnd()
            : base(tag.NumProps)
        {
            Initialize();
        }

        protected SessionEnd(int length)
            : base(length + tag.NumProps)
        {
            Initialize();
        }

        protected override bool EqualsTo(Cell other)
        {
            if (!base.EqualsTo(other))
            {
                return false;
            }
            return true;
        }

        public override int GetHashCode(Fingerprint fingerprint)
        {
            var hash = new Hash(base.GetHashCode(fingerprint));
            return hash.Code;
        }

        public override int GetTypeId()
        {
            return tag.TypeId;
        }

        public override Cell.Tag GetTypeTag() 
        {
            return tag;
        }

        public override Func<Event> GetFactoryMethod()
        {
            return SessionEnd.New;
        }

        protected override bool IsEquivalent(Cell other, Fingerprint fingerprint)
        {
            if (!base.IsEquivalent(other, fingerprint))
            {
                return false;
            }
            return true;
        }

        public override void Deserialize(Deserializer deserializer)
        {
            base.Deserialize(deserializer);
        }

        public override void Deserialize(VerboseDeserializer deserializer)
        {
            base.Deserialize(deserializer);
        }

        public override int GetLength(Type targetType, ref bool flag)
        {
            int length = base.GetLength(targetType, ref flag);
            if (!flag) { return length; }
            if (targetType != null && targetType == typeof(SessionEnd))
            {
                flag = false;
            }
            return length;
        }

        public override void Serialize(Serializer serializer,
            Type targetType, ref bool flag)
        {
            base.Serialize(serializer, targetType, ref flag);
            if (!flag) { return; }
            if (targetType != null && targetType == typeof(SessionEnd))
            {
                flag = false;
            }
        }

        public override void Serialize(VerboseSerializer serializer,
            Type targetType, ref bool flag)
        {
            base.Serialize(serializer, targetType, ref flag);
            if (!flag) { return; }
            if (targetType != null && targetType == typeof(SessionEnd))
            {
                flag = false;
            }
        }

        protected override void Describe(StringBuilder stringBuilder)
        {
            base.Describe(stringBuilder);
        }

        private void Initialize()
        {
        }
    }
}
